# Generated by Django 6.0.1 on 2026-01-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "target_type",
                    models.CharField(
                        choices=[("TOTAL_SPENDING", "총 지출"), ("TOTAL_INCOME", "총 수입")],
                        max_length=20,
                        verbose_name="분석 대상",
                    ),
                ),
                (
                    "period_unit",
                    models.CharField(
                        choices=[("DAILY", "일간"), ("WEEKLY", "주간"), ("MONTHLY", "월간"), ("YEARLY", "연간")],
                        max_length=10,
                        verbose_name="분석 주기",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("result_image_url", models.URLField(blank=True, max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
