# Generated by Django 6.0.1 on 2026-01-13 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='지출 분석', help_text='분석 내용', max_length=100)),
                ('type', models.CharField(default='매일', help_text='분석 기간 유형', max_length=50)),
                ('period_start', models.DateField(default=django.utils.timezone.now, verbose_name='분석 시작일')),
                ('period_end', models.DateField(default=django.utils.timezone.now, verbose_name='분석 종료일')),
                ('description', models.TextField(blank=True, verbose_name='데이터 분석 설명')),
                ('result_image', models.ImageField(upload_to='analysis_results/%Y/%m/', verbose_name='분석 그래프 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
