# Generated by Django 6.0.1 on 2026-01-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('balance_after_tx', models.BigIntegerField()),
                ('tx_detail', models.CharField(max_length=255)),
                ('tx_type', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounts.account')),
            ],
        ),
    ]
