# Generated by Django 6.0.1 on 2026-01-13 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20, verbose_name="거래 금액")),
                (
                    "balance_after_tx",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=20, verbose_name="거래 후 잔액"),
                ),
                ("tx_detail", models.CharField(max_length=255, verbose_name="거래 상세 내용")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "식비"),
                            ("TRANSPORT", "교통"),
                            ("LIVING", "주거/통신"),
                            ("HEALTH", "의료/건강"),
                            ("CULTURE", "문화/여가"),
                            ("EDUCATION", "교육"),
                            ("SAVING", "저축/투자"),
                            ("ETC", "기타"),
                        ],
                        default="ETC",
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("tx_type", models.CharField(max_length=10, verbose_name="거래 타입")),
                ("payment_method", models.CharField(max_length=15, verbose_name="결제 수단")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="거래 일시")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="accounts.account",
                        verbose_name="연결된 계좌",
                    ),
                ),
            ],
        ),
    ]
