# Generated by Django 6.0.1 on 2026-01-13 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='전화번호 형식이 올바르지 않습니다.', regex='^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})$')]),
        ),
    ]
